function object(value){return value&&typeof value==="object"&&!Array.isArray(value)?value:{};}
function text(value,label,{required=false,max=500}={}){if(value===undefined)return undefined;if(typeof value!=="string"||value.length>max||(required&&!value.trim()))throw new TypeError(`${label} is invalid`);return value;}
function number(value,label){if(value===undefined)return undefined;if(value!==null&&typeof value!=="number")throw new TypeError(`${label} is invalid`);return value;}
function stringArray(value,label){if(value===undefined)return undefined;if(!Array.isArray(value)||value.some(item=>typeof item!=="string"))throw new TypeError(`${label} is invalid`);return [...new Set(value)];}
function nextPosition(database,table,versionId){return database.prepare(`SELECT coalesce(max(position),-1)+1 AS position FROM ${table} WHERE version_id=?`).get(versionId).position;}
function dataRow(database,table,versionId,id){const row=database.prepare(`SELECT data_json AS dataJson FROM ${table} WHERE version_id=? AND external_id=?`).get(versionId,id);return row?object(JSON.parse(row.dataJson)):undefined;}
function mergeData(current,patch,keys){const result={...current};for(const [field,target] of Object.entries(keys))if(patch[field]!==undefined)result[target]=patch[field];return result;}
function requireTarget(database,table,versionId,id){if(!database.prepare(`SELECT 1 FROM ${table} WHERE version_id=? AND external_id=?`).get(versionId,id))throw new TypeError("Review target does not exist in current draft");}
function requireCreate(database,table,versionId,id){if(database.prepare(`SELECT 1 FROM ${table} WHERE version_id=? AND external_id=?`).get(versionId,id))throw new TypeError("Review create target already exists in current draft");}

function applyOverview(database,versionId,change){if(change.operation!=="update")throw new TypeError("Overview only supports update");const row=database.prepare("SELECT metadata_json AS metadataJson FROM project_versions WHERE id=?").get(versionId);const metadata=object(JSON.parse(row.metadataJson));if(change.patch.title!==undefined)metadata.title=text(change.patch.title,"title",{required:true,max:160});if(change.patch.summary!==undefined)metadata.summary=text(change.patch.summary,"summary",{max:4000});if(change.patch.status!==undefined)metadata.projectStatus=text(change.patch.status,"status",{required:true,max:80});database.prepare("UPDATE project_versions SET metadata_json=? WHERE id=?").run(JSON.stringify(metadata),versionId);}

function applyUnit(database,versionId,change){const table="project_units";if(change.operation==="delete")throw new TypeError("Unit delete is not allowed");if(change.operation==="create"){requireCreate(database,table,versionId,change.targetId);database.prepare("INSERT INTO project_units (version_id,external_id,position,name,data_json) VALUES (?,?,?,?,?)").run(versionId,change.targetId,nextPosition(database,table,versionId),text(change.patch.name,"name",{required:true,max:160}),JSON.stringify(mergeData({},change.patch,{description:"objective",owner:"owner"})));return;}requireTarget(database,table,versionId,change.targetId);const data=mergeData(dataRow(database,table,versionId,change.targetId),change.patch,{description:"objective",owner:"owner"});database.prepare("UPDATE project_units SET name=coalesce(?,name),data_json=? WHERE version_id=? AND external_id=?").run(text(change.patch.name,"name",{required:true,max:160})??null,JSON.stringify(data),versionId,change.targetId);}

function applyStage(database,versionId,change){const table="project_stages";if(change.operation==="delete")throw new TypeError("Roadmap delete is not allowed");if(change.operation==="create"){requireCreate(database,table,versionId,change.targetId);database.prepare("INSERT INTO project_stages (version_id,external_id,position,title,date_label,data_json) VALUES (?,?,?,?,?,?)").run(versionId,change.targetId,nextPosition(database,table,versionId),text(change.patch.title,"title",{required:true,max:160}),text(change.patch.date,"date",{max:10})??"",JSON.stringify(mergeData({},change.patch,{description:"description",state:"state"})));return;}requireTarget(database,table,versionId,change.targetId);const data=mergeData(dataRow(database,table,versionId,change.targetId),change.patch,{description:"description",state:"state"});database.prepare("UPDATE project_stages SET title=coalesce(?,title),date_label=coalesce(?,date_label),data_json=? WHERE version_id=? AND external_id=?").run(text(change.patch.title,"title",{required:true,max:160})??null,text(change.patch.date,"date",{max:10})??null,JSON.stringify(data),versionId,change.targetId);}

function taskBase(database,versionId,change){const table="project_tasks",p=change.patch;if(change.operation==="delete")return;if(change.operation==="create"){requireCreate(database,table,versionId,change.targetId);database.prepare(`INSERT INTO project_tasks (version_id,external_id,unit_external_id,parent_external_id,position,title,start_date,end_date,progress,data_json) VALUES (?,?,?,?,?,?,?,?,?,?)`).run(versionId,change.targetId,text(p.unitId,"unitId",{required:true,max:128}),text(p.parentId,"parentId",{max:128})||null,nextPosition(database,table,versionId),text(p.title,"title",{required:true,max:240}),text(p.startDate,"startDate",{max:10})??"",text(p.endDate,"endDate",{max:10})??"",number(p.progress,"progress")??null,JSON.stringify(mergeData({},p,{owner:"owner",state:"state",expectedOutput:"expectedOutput"})));return;}requireTarget(database,table,versionId,change.targetId);const current=dataRow(database,table,versionId,change.targetId),data=mergeData(current,p,{owner:"owner",state:"state",expectedOutput:"expectedOutput"});database.prepare(`UPDATE project_tasks SET unit_external_id=coalesce(?,unit_external_id),parent_external_id=CASE WHEN ?=1 THEN ? ELSE parent_external_id END,title=coalesce(?,title),start_date=coalesce(?,start_date),end_date=coalesce(?,end_date),progress=CASE WHEN ?=1 THEN ? ELSE progress END,data_json=? WHERE version_id=? AND external_id=?`).run(text(p.unitId,"unitId",{max:128})??null,p.parentId!==undefined?1:0,text(p.parentId,"parentId",{max:128})||null,text(p.title,"title",{required:true,max:240})??null,text(p.startDate,"startDate",{max:10})??null,text(p.endDate,"endDate",{max:10})??null,p.progress!==undefined?1:0,number(p.progress,"progress")??null,JSON.stringify(data),versionId,change.targetId);}

function taskLinks(database,versionId,change){if(change.operation==="delete")return;const dependencies=stringArray(change.patch.dependsOn,"dependsOn");if(dependencies===undefined)return;database.prepare("DELETE FROM task_links WHERE version_id=? AND task_external_id=?").run(versionId,change.targetId);const insert=database.prepare("INSERT INTO task_links (version_id,task_external_id,depends_on_external_id,position) VALUES (?,?,?,?)");dependencies.forEach((id,index)=>insert.run(versionId,change.targetId,id,index));}
function deleteTask(database,versionId,change){if(change.operation!=="delete")return;requireTarget(database,"project_tasks",versionId,change.targetId);const referenced=database.prepare(`SELECT (SELECT count(*) FROM project_tasks WHERE version_id=? AND parent_external_id=?)+(SELECT count(*) FROM task_links WHERE version_id=? AND depends_on_external_id=?)+(SELECT count(*) FROM workstream_tasks WHERE version_id=? AND task_external_id=?) AS count`).get(versionId,change.targetId,versionId,change.targetId,versionId,change.targetId).count;if(referenced)throw new TypeError("Task delete target is still referenced");database.prepare("DELETE FROM project_tasks WHERE version_id=? AND external_id=?").run(versionId,change.targetId);}

function applyOutcome(database,versionId,change){const table="project_closures",p=change.patch;if(change.operation==="delete")throw new TypeError("Outcome delete is not allowed");if(change.operation==="create"){requireCreate(database,table,versionId,change.targetId);database.prepare("INSERT INTO project_closures (version_id,external_id,position,title,date_label,data_json) VALUES (?,?,?,?,?,?)").run(versionId,change.targetId,nextPosition(database,table,versionId),text(p.title,"title",{required:true,max:160}),text(p.date,"date",{max:10})??"",JSON.stringify(mergeData({},p,{state:"state",description:"description",result:"result",source:"source"})));return;}requireTarget(database,table,versionId,change.targetId);const data=mergeData(dataRow(database,table,versionId,change.targetId),p,{state:"state",description:"description",result:"result",source:"source"});database.prepare("UPDATE project_closures SET title=coalesce(?,title),date_label=coalesce(?,date_label),data_json=? WHERE version_id=? AND external_id=?").run(text(p.title,"title",{required:true,max:160})??null,text(p.date,"date",{max:10})??null,JSON.stringify(data),versionId,change.targetId);}

function applyRisk(database,versionId,change){const table="project_risks",p=change.patch;if(change.operation==="delete"){requireTarget(database,table,versionId,change.targetId);database.prepare("DELETE FROM project_risks WHERE version_id=? AND external_id=?").run(versionId,change.targetId);return;}if(change.operation==="create"){requireCreate(database,table,versionId,change.targetId);database.prepare(`INSERT INTO project_risks (version_id,external_id,position,title,severity,status,owner,mitigation,due_date,source) VALUES (?,?,?,?,?,?,?,?,?,?)`).run(versionId,change.targetId,nextPosition(database,table,versionId),text(p.title,"title",{required:true,max:240}),text(p.severity,"severity",{required:true,max:20}),text(p.status,"status",{required:true,max:20}),text(p.owner,"owner",{max:160})??"",text(p.mitigation,"mitigation",{max:2000})??"",text(p.dueDate,"dueDate",{max:10})??"",text(p.source,"source",{max:500})??"");return;}requireTarget(database,table,versionId,change.targetId);database.prepare(`UPDATE project_risks SET title=coalesce(?,title),severity=coalesce(?,severity),status=coalesce(?,status),owner=coalesce(?,owner),mitigation=coalesce(?,mitigation),due_date=coalesce(?,due_date),source=coalesce(?,source) WHERE version_id=? AND external_id=?`).run(...[text(p.title,"title",{required:true,max:240}),text(p.severity,"severity",{max:20}),text(p.status,"status",{max:20}),text(p.owner,"owner",{max:160}),text(p.mitigation,"mitigation",{max:2000}),text(p.dueDate,"dueDate",{max:10}),text(p.source,"source",{max:500})].map(value=>value??null),versionId,change.targetId);}

function applyMetric(database,versionId,change){const table="project_metrics",p=change.patch;if(change.operation==="delete")throw new TypeError("Metric delete is not allowed");const encoded=value=>value===undefined?undefined:JSON.stringify(value);if(change.operation==="create"){requireCreate(database,table,versionId,change.targetId);database.prepare(`INSERT INTO project_metrics (version_id,external_id,position,name,value_json,unit,status,as_of,target_json,source) VALUES (?,?,?,?,?,?,?,?,?,?)`).run(versionId,change.targetId,nextPosition(database,table,versionId),text(p.name,"name",{required:true,max:160}),encoded(p.value)??null,text(p.unit,"unit",{max:80})??"",text(p.status,"status",{required:true,max:20}),text(p.asOf,"asOf",{max:10})??"",encoded(p.target)??null,text(p.source,"source",{max:500})??"");return;}requireTarget(database,table,versionId,change.targetId);database.prepare(`UPDATE project_metrics SET name=coalesce(?,name),value_json=CASE WHEN ?=1 THEN ? ELSE value_json END,unit=coalesce(?,unit),status=coalesce(?,status),as_of=coalesce(?,as_of),target_json=CASE WHEN ?=1 THEN ? ELSE target_json END,source=coalesce(?,source) WHERE version_id=? AND external_id=?`).run(text(p.name,"name",{required:true,max:160})??null,p.value!==undefined?1:0,encoded(p.value)??null,text(p.unit,"unit",{max:80})??null,text(p.status,"status",{max:20})??null,text(p.asOf,"asOf",{max:10})??null,p.target!==undefined?1:0,encoded(p.target)??null,text(p.source,"source",{max:500})??null,versionId,change.targetId);}

export function applyReviewedChanges(database,versionId,changes){const tasks=changes.filter(item=>["task-network","gantt"].includes(item.module));for(const change of changes.filter(item=>!["task-network","gantt"].includes(item.module))){if(change.module==="overview")applyOverview(database,versionId,change);else if(change.module==="units")applyUnit(database,versionId,change);else if(change.module==="roadmap")applyStage(database,versionId,change);else if(change.module==="outcomes")applyOutcome(database,versionId,change);else if(change.module==="risks")applyRisk(database,versionId,change);else if(change.module==="metrics")applyMetric(database,versionId,change);else throw new TypeError("Unsupported review module");}for(const change of tasks)taskBase(database,versionId,change);for(const change of tasks)taskLinks(database,versionId,change);for(const change of tasks)deleteTask(database,versionId,change);return versionId;}
