import assert from "node:assert/strict";
import test from "node:test";
import { createFakeProvider } from "../src/ai/providers/fake-provider.mjs";
import { createDisabledProvider } from "../src/ai/providers/disabled-provider.mjs";
import { openDatabase } from "../src/db/database.mjs";
import { applyMigrations } from "../src/db/migrate.mjs";
import { createGenerationService } from "../src/proposals/generation-service.mjs";

const at="2026-07-18T00:00:00.000Z";
function setup(){const db=openDatabase(":memory:");applyMigrations(db);db.prepare("INSERT INTO users (id,display_name,status,created_at,updated_at) VALUES ('editor','Editor','active',?,?)").run(at,at);db.prepare("INSERT INTO projects (id,name,template_id,template_version,created_at,updated_at) VALUES ('project-a','Project','standard-project-v1','1.0.0',?,?)").run(at,at);for(const layer of ["published","draft"]){db.prepare("INSERT INTO project_versions (project_id,layer,version_label,metadata_json,created_at) VALUES ('project-a',?,?,?,?)").run(layer,layer==="published"?"v1":"draft",JSON.stringify({title:"Project",version:layer==="published"?"v1":"draft"}),at);}const versions=db.prepare("SELECT id,layer FROM project_versions WHERE project_id='project-a'").all();for(const value of versions)db.prepare(`UPDATE projects SET ${value.layer==="published"?"published_version_id":"draft_version_id"}=? WHERE id='project-a'`).run(value.id);const published=versions.find(v=>v.layer==="published").id;db.prepare("INSERT INTO project_units (version_id,external_id,position,name,data_json) VALUES (?,'unit-a',0,'Team','{}')").run(published);db.prepare(`INSERT INTO project_materials (id,project_id,display_name,canonical_extension,canonical_mime,sha256,byte_size,status,active_extraction_version,created_by,created_at,updated_at) VALUES ('material-00000001','project-a','notes.txt','.txt','text/plain',?,20,'ready',1,'editor',?,?)`).run("a".repeat(64),at,at);db.prepare("INSERT INTO material_update_selections (project_id,material_id,template_id,template_version,selected_by,selected_at) VALUES ('project-a','material-00000001','meeting-notes','1.0.0','editor',?)").run(at);db.prepare("INSERT INTO material_generation_grants (project_id,material_id,enabled,granted_by,granted_at) VALUES ('project-a','material-00000001',1,'editor',?)").run(at);db.prepare(`INSERT INTO evidence_blocks (external_id,project_id,material_id,extraction_version,ordinal,kind,location_json,text,content_hash,created_at) VALUES ('evidence-00000001','project-a','material-00000001',1,0,'paragraph','{"paragraph":1}','需要整理数据。',?,?)`).run("b".repeat(64),at);return db;}
function provider(){return createFakeProvider(request=>{const input=JSON.parse(request.messages[1].content);const envelope=input.server_envelope;return{content:JSON.stringify({schemaVersion:envelope.schemaVersion,projectId:envelope.projectId,baseVersionId:envelope.baseVersionId,template:envelope.template,materialIds:envelope.materialIds,summary:"形成行动任务。",changes:[{changeId:"change-001",module:"task-network",operation:"create",targetId:"task-new-001",semanticType:"plan",patch:{title:"整理数据",unitId:"unit-a"},evidenceIds:[input.untrusted_evidence[0].evidenceId],confidence:0.8,warnings:[]}],warnings:[]}),usage:{input:100,output:50}};});}

test("generation persists one validated proposal atomically and never changes version pointers",async()=>{const db=setup();try{const before=db.prepare("SELECT published_version_id AS published,draft_version_id AS draft FROM projects WHERE id='project-a'").get();const service=createGenerationService(db,{provider:provider(),pricing:{inputMicrosPerMillion:10_000,outputMicrosPerMillion:20_000,currency:"CNY",version:"test"}});const job=service.createJob({id:"editor"},{projectId:"project-a",materialIds:["material-00000001"],idempotencyKey:"request-0001"});const duplicate=service.createJob({id:"editor"},{projectId:"project-a",materialIds:["material-00000001"],idempotencyKey:"request-0001"});assert.equal(duplicate.id,job.id);const done=await service.processJob("project-a",job.id);assert.equal(done.state,"succeeded");assert.ok(done.proposalId);assert.equal(db.prepare("SELECT count(*) AS count FROM change_proposal_items").get().count,1);assert.deepEqual(db.prepare("SELECT published_version_id AS published,draft_version_id AS draft FROM projects WHERE id='project-a'").get(),before);assert.equal(done.attempts[0].costStatus,"priced");}finally{db.close();}});

test("disabled provider is durable and retryable without partial proposal",async()=>{const db=setup();try{const service=createGenerationService(db,{provider:createDisabledProvider()});const job=service.createJob({id:"editor"},{projectId:"project-a",materialIds:["material-00000001"],idempotencyKey:"request-0002"});const done=await service.processJob("project-a",job.id);assert.equal(done.state,"failed_retryable");assert.equal(done.errorCode,"AI_PROVIDER_DISABLED");assert.equal(db.prepare("SELECT count(*) AS count FROM change_proposals").get().count,0);}finally{db.close();}});

test("stale published base fails before provider and does not rebase",async()=>{const db=setup();try{const fake=provider();const service=createGenerationService(db,{provider:fake});const job=service.createJob({id:"editor"},{projectId:"project-a",materialIds:["material-00000001"],idempotencyKey:"request-0003"});db.prepare("INSERT INTO project_versions (project_id,layer,version_label,metadata_json,created_at) VALUES ('project-a','published','v2','{\"title\":\"Project\",\"version\":\"v2\"}',?)").run(at);const next=db.prepare("SELECT max(id) AS id FROM project_versions").get().id;db.prepare("UPDATE projects SET published_version_id=? WHERE id='project-a'").run(next);const done=await service.processJob("project-a",job.id);assert.equal(done.state,"stale");assert.equal(fake.calls.length,0);assert.equal(done.baseVersionId,job.baseVersionId);}finally{db.close();}});

test("invalid provider structure receives one repair attempt then fails closed",async()=>{const db=setup();try{const fake=createFakeProvider(()=>({content:"{}",usage:{output:1}}));const service=createGenerationService(db,{provider:fake});const job=service.createJob({id:"editor"},{projectId:"project-a",materialIds:["material-00000001"],idempotencyKey:"request-0004"});const done=await service.processJob("project-a",job.id);assert.equal(done.state,"failed_terminal");assert.equal(fake.calls.length,2);assert.equal(done.attempts.length,2);assert.equal(db.prepare("SELECT count(*) AS count FROM change_proposals").get().count,0);}finally{db.close();}});
