import assert from "node:assert/strict";
import test from "node:test";
import { openDatabase } from "../src/db/database.mjs";
import { applyMigrations } from "../src/db/migrate.mjs";
import { buildGenerationContext } from "../src/proposals/context-builder.mjs";
import { validateProposal } from "../src/proposals/validator.mjs";

const at="2026-07-18T00:00:00.000Z";
function setup(){const db=openDatabase(":memory:");applyMigrations(db);db.prepare("INSERT INTO users (id,display_name,status,created_at,updated_at) VALUES ('editor','Editor','active',?,?)").run(at,at);for(const projectId of ["project-a","project-b"]){db.prepare("INSERT INTO projects (id,name,template_id,template_version,created_at,updated_at) VALUES (?,?,'standard-project-v1','1.0.0',?,?)").run(projectId,projectId,at,at);db.prepare("INSERT INTO project_versions (project_id,layer,version_label,metadata_json,created_at) VALUES (?,'published','v1','{\"title\":\"Project\",\"version\":\"v1\"}',?)").run(projectId,at);const version=db.prepare("SELECT id FROM project_versions WHERE project_id=?").get(projectId).id;db.prepare("UPDATE projects SET published_version_id=? WHERE id=?").run(version,projectId);db.prepare("INSERT INTO project_units (version_id,external_id,position,name,data_json) VALUES (?,'unit-a',0,'Team','{}')").run(version);
db.prepare("INSERT OR IGNORE INTO project_cards (version_id,external_id,element_type,position,title,owner,state,objective,start_date,end_date,progress,health,unit_id,parent_id,depends_on,card_attrs,created_at,updated_at) VALUES (?,'unit-a','unit',0,'Team','','','','','',NULL,'','','','[]','{}',?,?)").run(version,at,at);const material=`material-${projectId}-01`;db.prepare(`INSERT INTO project_materials (id,project_id,display_name,canonical_extension,canonical_mime,sha256,byte_size,status,active_extraction_version,created_by,created_at,updated_at) VALUES (?,?,'notes.txt','.txt','text/plain',?,20,'ready',1,'editor',?,?)`).run(material,projectId,(projectId==="project-a"?"a":"b").repeat(64),at,at);db.prepare("INSERT INTO material_update_selections (project_id,material_id,template_id,template_version,selected_by,selected_at) VALUES (?,?,'meeting-notes','1.0.0','editor',?)").run(projectId,material,at);db.prepare("INSERT INTO material_generation_grants (project_id,material_id,enabled,granted_by,granted_at) VALUES (?,?,1,'editor',?)").run(projectId,material,at);db.prepare(`INSERT INTO evidence_blocks (external_id,project_id,material_id,extraction_version,ordinal,kind,location_json,text,content_hash,created_at) VALUES (?,?,?,1,0,'paragraph','{"paragraph":1}','需要整理数据。',?,?)`).run(`evidence-${projectId}-01`,projectId,material,(projectId==="project-a"?"c":"d").repeat(64),at);}return db;}
function proposal(context){return{schemaVersion:"change-proposal-v1@1.0.0",projectId:context.projectId,baseVersionId:context.baseVersionId,template:{id:context.templateId,version:context.templateVersion},materialIds:context.materials.map(item=>item.id),summary:"形成行动任务。",changes:[{changeId:"change-001",module:"task-network",operation:"create",targetId:"task-new-001",semanticType:"plan",patch:{title:"整理数据",unitId:"unit-a",dependsOn:[],startDate:"2026-07-20",endDate:"2026-07-21"},evidenceIds:[context.evidence[0].evidenceId],confidence:0.8,warnings:[]}],warnings:[]};}

test("validator accepts an evidence-backed delta and adds deterministic warnings",()=>{const db=setup();try{const context=buildGenerationContext(db,{projectId:"project-a",materialIds:["material-project-a-01"]});const value=proposal(context);value.changes[0].patch.owner="王老师";const result=validateProposal(value,context);assert.equal(result.validation.taskGraph,true);assert.ok(result.warnings.includes("HIGH_IMPACT_FIELD"));}finally{db.close();}});

test("validator rejects cross-project evidence, stale envelope and unsupported fields",()=>{const db=setup();try{const context=buildGenerationContext(db,{projectId:"project-a",materialIds:["material-project-a-01"]});for(const mutate of [value=>value.projectId="project-b",value=>value.changes[0].evidenceIds=["evidence-project-b-01"],value=>value.changes[0].patch={title:"x",unitId:"unit-a",unknownField:"x"}]){const value=proposal(context);mutate(value);assert.throws(()=>validateProposal(value,context));}}finally{db.close();}});

test("validator rejects invalid dates, duplicate names and task cycles",()=>{const db=setup();try{const context=buildGenerationContext(db,{projectId:"project-a",materialIds:["material-project-a-01"]});const dates=proposal(context);dates.changes[0].patch.startDate="2026-08-02";dates.changes[0].patch.endDate="2026-08-01";assert.throws(()=>validateProposal(dates,context),error=>error.code==="INVALID_DATE_RANGE");const cycle=proposal(context);cycle.changes.push({changeId:"change-002",module:"task-network",operation:"create",targetId:"task-new-002",semanticType:"plan",patch:{title:"复核数据",unitId:"unit-a",dependsOn:["task-new-001"]},evidenceIds:[context.evidence[0].evidenceId],confidence:0.8,warnings:[]});cycle.changes[0].patch.dependsOn=["task-new-002"];assert.throws(()=>validateProposal(cycle,context),error=>error.code==="TASK_GRAPH_CYCLE");const duplicate=proposal(context);duplicate.changes.push({...structuredClone(duplicate.changes[0]),changeId:"change-002",targetId:"task-new-002"});assert.throws(()=>validateProposal(duplicate,context),error=>error.code==="DUPLICATE_NAME");}finally{db.close();}});

test("validator rejects task edits that reference a missing unit",()=>{const db=setup();try{const context=buildGenerationContext(db,{projectId:"project-a",materialIds:["material-project-a-01"]});const value=proposal(context);value.changes[0].patch.unitId="missing-unit";assert.throws(()=>validateProposal(value,context),error=>error.code==="TASK_UNIT_NOT_FOUND");}finally{db.close();}});

test("context builder requires grants, same template/current generation and project ownership",()=>{const db=setup();try{db.prepare("UPDATE material_generation_grants SET enabled=0 WHERE project_id='project-a'").run();assert.throws(()=>buildGenerationContext(db,{projectId:"project-a",materialIds:["material-project-a-01"]}),error=>error.code==="GENERATION_NOT_GRANTED");assert.throws(()=>buildGenerationContext(db,{projectId:"project-a",materialIds:["material-project-b-01"]}),error=>error.code==="MATERIAL_NOT_FOUND");}finally{db.close();}});
