import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import test from "node:test";

const app=readFileSync(new URL("../public/app.js",import.meta.url),"utf8");const renderers=readFileSync(new URL("../public/modules/renderers.js",import.meta.url),"utf8");const shared=readFileSync(new URL("../public/modules/shared.js",import.meta.url),"utf8");const css=readFileSync(new URL("../public/styles.css",import.meta.url),"utf8");const source=`${app}\n${renderers}`;

test("proposal workspace uses canonical project-scoped task and proposal routes",()=>{for(const contract of ["/generation-tasks","/capabilities","/retry","/change-proposals","generationTaskId","proposalId"])assert.match(source,new RegExp(contract.replaceAll("/","\\/")));assert.match(app,/generationTaskMatch/);assert.match(app,/proposalMatch/);assert.match(renderers,/mutation: true/);});

test("project update starts with material and binds later steps to concrete instances",()=>{for(const copy of ["先提交本次更新材料","上传本次更新材料","处理与生成","模拟路线图","审核与发布","更新后的项目路线图","审核本次更新"])assert.match(source,new RegExp(copy.replace(/[.*+?^${}()|[\]\\]/g,"\\$&")));for(const route of ["/preview/","/proposals/","/generation-tasks/"])assert.match(source,new RegExp(route.replaceAll("/","\\/")));assert.match(renderers,/function renderUpdateStartWorkspace/);assert.match(renderers,/previewHref\(context,task\.proposalId\)/);assert.match(renderers,/panel\.replaceChildren\(renderRoadmapSwimlane\(previewContext\)\)/);assert.doesNotMatch(renderers,/className: "ai-preview-(?:stage|task)/);assert.doesNotMatch(renderers,/text:"生成与核对"|className:"proposal-list"|className:"generation-task-list"/);assert.doesNotMatch(source,/innerHTML|insertAdjacentHTML|eval\(|new Function/);});

test("update roadmap cards expose scoped editing and exact delete confirmation",()=>{for(const contract of ["当前节点 · 只读","保存预览修改","删除本次预览卡片","确认删除","update-preview-readonly","roadmapPreview"])assert.match(source,new RegExp(contract.replace(/[.*+?^${}()|[\]\\]/g,"\\$&")));assert.match(renderers,/options\.scope === "preview"/);assert.match(renderers,/decision: "rejected"/);assert.match(renderers,/preview\/\$\{encodeURIComponent\(options\.change\.changeId\)\}/);});

test("roadmap and familiar tools use the shared icon language without pasted glyphs",()=>{assert.match(shared,/const LUCIDE_ICONS/);assert.match(shared,/export function icon/);assert.match(renderers,/icon\("pencil", \{ size: 14 \}\)/);assert.match(renderers,/icon\("chevron-down", \{ size: 12 \}\)/);for(const iconName of ["upload","message-square","square-pen"])assert.match(app,new RegExp(`iconName: "${iconName}"`));assert.doesNotMatch(renderers,/text:\s*["']编辑["']/);assert.doesNotMatch(app,/icon:\s*["'](?:↑|···|\\+)["']/);assert.match(css,/\.roadmap-card-edit-button\s*\{[^}]*border-radius:\s*50%/s);assert.match(css,/\.swimlane-stage-cell > \.roadmap-card-edit-button\s*\{[^}]*position:\s*absolute/s);assert.match(css,/\.swimlane-task-card\s*\{[^}]*min-width:\s*0[^}]*max-width:\s*100%/s);});

test("generation sheet enforces same-template bounded material selection and server capabilities",()=>{for(const contract of ["maxMaterialsPerTask","maxEvidenceBlocks","generationEnabled","updateTemplateKey","idempotencyKey","crypto.randomUUID","caps.create","capabilityEnvelope.provider?.enabled"])assert.match(renderers,new RegExp(contract.replace(/[.?]/g,match=>`\\${match}`)));for(const copy of ["已选择","与已选材料模板不同","暂无可用于生成的材料","正在创建生成任务…","关闭生成面板","更新生成当前未启用；材料和已有建议仍可查看。"])assert.match(renderers,new RegExp(copy.replace(/[.*+?^${}()|[\]\\]/g,"\\$&")));assert.doesNotMatch(renderers,/evidenceCount\\s*>\\s*maxEvidence/);});

test("Phase 6 UI keeps review, merge, publish and rollback on canonical controlled routes",()=>{for(const contract of ["接受此项","驳回此项","编辑后接受","应用到草稿","受控发布","回滚到直接上一发布版本","/review/","/merge","/release","/publish","/rollback"])assert.match(renderers,new RegExp(contract.replace(/[.*+?^${}()|[\]\\]/g,"\\$&")));assert.match(renderers,/AI 无法执行这些动作/);assert.match(renderers,/AI 预览不能直达发布/);assert.doesNotMatch(source,/innerHTML|insertAdjacentHTML|eval\(|new Function/);});

test("project update and review UI preserve desktop, tablet and mobile layouts",()=>{for(const contract of [/\.project-update-flow-steps/,/\.project-update-intake/,/\.generation-sheet/,/\.generation-detail-layout/,/\.proposal-detail-layout/,/\.proposal-change-index/,/\.proposal-evidence-list/,/\.project-update-roadmap/,/\.project-update-status/,/\.update-preview-readonly/,/@media \(max-width: 1279px\)/,/@media \(max-width: 767px\)/])assert.match(css,contract);assert.match(css,/grid-template-columns:\s*280px minmax\(0,1fr\)/);assert.match(css,/min-height:\s*40px/);});

test("proposal evidence preserves deterministic manual, line, slide and JSON locators",()=>{for(const contract of [/人工材料/,/location\.line/,/location\.slide/,/location\.pointer/])assert.match(renderers,contract);});
