import assert from "node:assert/strict";
import { createServer } from "node:http";
import { mkdtempSync, readFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import test from "node:test";
import { createFakeProvider } from "../src/ai/providers/fake-provider.mjs";
import { openDatabase } from "../src/db/database.mjs";
import { applyMigrations } from "../src/db/migrate.mjs";
import { createApp } from "../src/http/app.mjs";
import { importLegacyProject } from "../src/migration/legacy-project.mjs";
import { createAuthRepository } from "../src/repositories/auth-repository.mjs";
import { hashPassword } from "../src/security/passwords.mjs";
import { createAuthService } from "../src/services/auth-service.mjs";

const fixture=JSON.parse(readFileSync(new URL("../fixtures/projects/xugu-agentic-group.json",import.meta.url),"utf8"));const password="proposal-api-password";const at="2026-07-18T00:00:00.000Z";
function addUser(db,id,login,role,projects=[]){createAuthRepository(db).insertUser({id,displayName:login,loginName:login,...hashPassword(password),createdAt:at,updatedAt:at});for(const projectId of projects)db.prepare("INSERT INTO project_members (project_id,user_id,role,created_at) VALUES (?,?,?,?)").run(projectId,id,role,at);}
async function setup(){const directory=mkdtempSync(join(tmpdir(),"proposal-api-"));const database=openDatabase(join(directory,"db.sqlite"));applyMigrations(database);importLegacyProject(database,fixture,{projectId:"xugu-agentic-group",now:at});importLegacyProject(database,fixture,{projectId:"other-project",name:"Other",now:at});const authService=createAuthService(database);authService.ensureBootstrapAdmin({loginName:"admin",password,displayName:"Admin"});addUser(database,"viewer","viewer","viewer",["xugu-agentic-group"]);addUser(database,"editor","editor","project_editor",["xugu-agentic-group"]);addUser(database,"padmin","project-admin","project_admin",["xugu-agentic-group"]);addUser(database,"outsider","outsider","viewer",[]);const provider=createFakeProvider(request=>{const input=JSON.parse(request.messages[1].content);const envelope=input.server_envelope;return{content:JSON.stringify({schemaVersion:envelope.schemaVersion,projectId:envelope.projectId,baseVersionId:envelope.baseVersionId,template:envelope.template,materialIds:envelope.materialIds,summary:"新增行动任务。",changes:[{changeId:"change-001",module:"task-network",operation:"create",targetId:"proposal-task-001",semanticType:"plan",patch:{title:"跟进数据治理",unitId:"rd"},evidenceIds:[input.untrusted_evidence[0].evidenceId],confidence:0.82,warnings:[]}],warnings:[]}),usage:{input:100,output:50}};});const server=createServer(createApp({database,authService,materialOptions:{storageRoot:join(directory,"storage")},proposalOptions:{provider,syncProcess:true}}));await new Promise((resolve,reject)=>{server.once("error",reject);server.listen(0,"127.0.0.1",resolve);});return{database,provider,baseUrl:`http://127.0.0.1:${server.address().port}`,async close(){await new Promise(resolve=>server.close(resolve));database.close();}};}
async function api(c,path,options={}){const headers={...(options.headers??{})};if(options.session)headers.cookie=options.session.cookie;if(options.csrf)headers["x-csrf-token"]=options.csrf;let body;if(options.body!==undefined){headers["content-type"]="application/json";body=JSON.stringify(options.body);}const response=await fetch(`${c.baseUrl}${path}`,{method:options.method??"GET",headers,body});const text=await response.text();return{response,payload:text?JSON.parse(text):null};}
async function login(c,name){const result=await api(c,"/api/login",{method:"POST",body:{loginName:name,password}});return{cookie:result.response.headers.get("set-cookie").split(";",1)[0],csrf:result.payload.csrfToken};}
async function createMaterial(c,editor){const created=await api(c,"/api/projects/xugu-agentic-group/materials/manual",{method:"POST",session:editor,csrf:editor.csrf,body:{title:"战情纪要",body:"数据治理行动任务需要由第一作战单元跟进。",updateTemplateId:"meeting-notes"}});assert.equal(created.response.status,201);return created.payload.material.id;}

test("generation capability, grant, create and proposal detail are project scoped",async()=>{const c=await setup();try{const editor=await login(c,"editor"),admin=await login(c,"project-admin"),viewer=await login(c,"viewer");const id=await createMaterial(c,editor);const caps=await api(c,"/api/projects/xugu-agentic-group/generation-tasks/capabilities",{session:editor});assert.equal(caps.response.status,200);assert.equal(caps.payload.capabilities.create,true);assert.equal(caps.payload.provider.enabled,true);assert.equal(caps.payload.eligibleMaterials[0].generation.enabled,true);assert.ok(["ready","warning"].includes(caps.payload.eligibleMaterials[0].readiness.status));assert.equal((await api(c,`/api/projects/xugu-agentic-group/materials/${id}/generation`,{method:"PATCH",session:editor,csrf:editor.csrf,body:{enabled:false}})).response.status,404);const revoked=await api(c,`/api/projects/xugu-agentic-group/materials/${id}/generation`,{method:"PATCH",session:admin,csrf:admin.csrf,body:{enabled:false}});assert.equal(revoked.response.status,200);assert.equal(revoked.payload.material.generation.enabled,false);const grant=await api(c,`/api/projects/xugu-agentic-group/materials/${id}/generation`,{method:"PATCH",session:admin,csrf:admin.csrf,body:{enabled:true}});assert.equal(grant.response.status,200);assert.equal(grant.payload.material.generation.enabled,true);const created=await api(c,"/api/projects/xugu-agentic-group/generation-tasks",{method:"POST",session:editor,csrf:editor.csrf,body:{materialIds:[id],idempotencyKey:"proposal-request-001"}});assert.equal(created.response.status,202);assert.equal(created.payload.task.state,"succeeded");const jobId=created.payload.task.id,proposalId=created.payload.task.proposalId;const duplicate=await api(c,"/api/projects/xugu-agentic-group/generation-tasks",{method:"POST",session:editor,csrf:editor.csrf,body:{materialIds:[id],idempotencyKey:"proposal-request-001"}});assert.equal(duplicate.payload.task.id,jobId);assert.equal(c.provider.calls.length,1);const detail=await api(c,`/api/projects/xugu-agentic-group/change-proposals/${proposalId}`,{session:viewer});assert.equal(detail.response.status,200);assert.equal(detail.payload.proposal.changes[0].evidence.length,1);assert.equal(detail.payload.proposal.status,"pending");assert.equal(c.database.prepare("SELECT count(*) AS count FROM audit_events WHERE action LIKE 'generation.%'").get().count>=2,true);assert.equal(c.database.prepare("SELECT count(*) AS count FROM project_versions").get().count,4);}finally{await c.close();}});

test("roles, CSRF and cross-project object guesses fail closed",async()=>{const c=await setup();try{const editor=await login(c,"editor"),admin=await login(c,"project-admin"),viewer=await login(c,"viewer"),outsider=await login(c,"outsider");const id=await createMaterial(c,editor);await api(c,`/api/projects/xugu-agentic-group/materials/${id}/generation`,{method:"PATCH",session:admin,csrf:admin.csrf,body:{enabled:true}});assert.equal((await api(c,"/api/projects/xugu-agentic-group/generation-tasks",{method:"POST",session:editor,body:{materialIds:[id],idempotencyKey:"proposal-request-002"}})).response.status,403);assert.equal((await api(c,"/api/projects/xugu-agentic-group/generation-tasks",{method:"POST",session:viewer,csrf:viewer.csrf,body:{materialIds:[id],idempotencyKey:"proposal-request-003"}})).response.status,404);const created=await api(c,"/api/projects/xugu-agentic-group/generation-tasks",{method:"POST",session:editor,csrf:editor.csrf,body:{materialIds:[id],idempotencyKey:"proposal-request-004"}});const taskId=created.payload.task.id,proposalId=created.payload.task.proposalId;assert.equal((await api(c,`/api/projects/other-project/generation-tasks/${taskId}`,{session:editor})).response.status,404);assert.equal((await api(c,`/api/projects/other-project/change-proposals/${proposalId}`,{session:editor})).response.status,404);assert.equal((await api(c,"/api/projects/xugu-agentic-group/generation-tasks",{session:outsider})).response.status,404);}finally{await c.close();}});

test("viewer reads validated proposals while review mutations remain admin-only",async()=>{const c=await setup();try{const editor=await login(c,"editor"),admin=await login(c,"project-admin"),viewer=await login(c,"viewer");const id=await createMaterial(c,editor);await api(c,`/api/projects/xugu-agentic-group/materials/${id}/generation`,{method:"PATCH",session:admin,csrf:admin.csrf,body:{enabled:true}});const created=await api(c,"/api/projects/xugu-agentic-group/generation-tasks",{method:"POST",session:editor,csrf:editor.csrf,body:{materialIds:[id],idempotencyKey:"proposal-request-005"}});const proposalId=created.payload.task.proposalId;assert.equal((await api(c,"/api/projects/xugu-agentic-group/change-proposals",{session:viewer})).payload.items.length,1);const review=await api(c,`/api/projects/xugu-agentic-group/change-proposals/${proposalId}/review`,{session:viewer});assert.equal(review.response.status,200);assert.equal(review.payload.capabilities.review,false);assert.equal((await api(c,`/api/projects/xugu-agentic-group/change-proposals/${proposalId}/review/change-001`,{method:"PATCH",session:viewer,csrf:viewer.csrf,body:{decision:"accepted"}})).response.status,404);assert.equal(c.database.prepare("SELECT status FROM change_proposals WHERE id=?").get(proposalId).status,"pending");}finally{await c.close();}});
