import assert from "node:assert/strict";
import { createServer } from "node:http";
import { readFileSync } from "node:fs";
import test from "node:test";
import { createFakeProvider } from "../src/ai/providers/fake-provider.mjs";
import { openDatabase } from "../src/db/database.mjs";
import { applyMigrations } from "../src/db/migrate.mjs";
import { createApp } from "../src/http/app.mjs";
import { importLegacyProject } from "../src/migration/legacy-project.mjs";
import { createAuthRepository } from "../src/repositories/auth-repository.mjs";
import { hashPassword } from "../src/security/passwords.mjs";
import { createAuthService } from "../src/services/auth-service.mjs";

const fixture=JSON.parse(readFileSync(new URL("../fixtures/projects/xugu-agentic-group.json",import.meta.url),"utf8")),at="2026-07-18T00:00:00.000Z",password="review-api-password";
function addUser(db,id,login,role,projectId="xugu-agentic-group"){createAuthRepository(db).insertUser({id,displayName:login,loginName:login,...hashPassword(password),createdAt:at,updatedAt:at});db.prepare("INSERT INTO project_members (project_id,user_id,role,created_at) VALUES (?,?,?,?)").run(projectId,id,role,at);}
async function setup(){const database=openDatabase(":memory:");applyMigrations(database);importLegacyProject(database,fixture,{projectId:"xugu-agentic-group",now:at});importLegacyProject(database,fixture,{projectId:"other-project",name:"Other",now:at});const auth=createAuthService(database);auth.ensureBootstrapAdmin({loginName:"admin",password,displayName:"Admin"});addUser(database,"viewer","viewer","viewer");addUser(database,"editor","editor","project_editor");addUser(database,"padmin","project-admin","project_admin");const provider=createFakeProvider(request=>{const input=JSON.parse(request.messages[1].content),e=input.server_envelope;return{content:JSON.stringify({schemaVersion:e.schemaVersion,projectId:e.projectId,baseVersionId:e.baseVersionId,template:e.template,materialIds:e.materialIds,summary:"审核 API 提案",changes:[{changeId:"change-001",module:"task-network",operation:"create",targetId:"api-review-task",semanticType:"plan",patch:{title:"审核 API 任务",unitId:"rd"},evidenceIds:[input.untrusted_evidence[0].evidenceId],confidence:.8,warnings:[]}],warnings:[]}),usage:{input:10,output:10}};});const server=createServer(createApp({database,authService:auth,proposalOptions:{provider,now:()=>Date.parse(at)},reviewOptions:{now:()=>Date.parse(at)},releaseOptions:{now:()=>Date.parse(at)}}));await new Promise(resolve=>server.listen(0,"127.0.0.1",resolve));return{database,baseUrl:`http://127.0.0.1:${server.address().port}`,async close(){await new Promise(resolve=>server.close(resolve));database.close();}};}
async function api(c,path,o={}){const headers={};if(o.session)headers.cookie=o.session.cookie;if(o.csrf)headers["x-csrf-token"]=o.csrf;let body;if(o.body!==undefined){headers["content-type"]="application/json";body=JSON.stringify(o.body);}const response=await fetch(c.baseUrl+path,{method:o.method??"GET",headers,body});const text=await response.text();return{response,payload:text?JSON.parse(text):null};}
async function login(c,name){const r=await api(c,"/api/login",{method:"POST",body:{loginName:name,password}});return{cookie:r.response.headers.get("set-cookie").split(";",1)[0],csrf:r.payload.csrfToken};}
async function proposal(c,editor,admin){const made=await api(c,"/api/projects/xugu-agentic-group/materials/manual",{method:"POST",session:editor,csrf:editor.csrf,body:{title:"审核 API 纪要",body:"第一作战单元需要执行审核 API 任务。",updateTemplateId:"meeting-notes"}}),id=made.payload.material.id;await api(c,`/api/projects/xugu-agentic-group/materials/${id}/generation`,{method:"PATCH",session:admin,csrf:admin.csrf,body:{enabled:true}});return(await api(c,"/api/projects/xugu-agentic-group/generation-tasks",{method:"POST",session:editor,csrf:editor.csrf,body:{materialIds:[id],idempotencyKey:"review-api-seed"}})).payload.task.proposalId;}

test("review, merge, publish, audit and rollback APIs enforce roles and CSRF",async()=>{const c=await setup();try{const editor=await login(c,"editor"),admin=await login(c,"project-admin"),viewer=await login(c,"viewer"),id=await proposal(c,editor,admin);assert.equal((await api(c,`/api/projects/xugu-agentic-group/change-proposals/${id}/review/change-001`,{method:"PATCH",session:admin,body:{decision:"accepted"}})).response.status,403);assert.equal((await api(c,`/api/projects/xugu-agentic-group/change-proposals/${id}/review/change-001`,{method:"PATCH",session:editor,csrf:editor.csrf,body:{decision:"accepted"}})).response.status,404);assert.equal((await api(c,`/api/projects/xugu-agentic-group/change-proposals/${id}/review/change-001`,{method:"PATCH",session:admin,csrf:admin.csrf,body:{decision:"accepted",patch:{title:"已审核 API 任务",unitId:"rd"}}})).response.status,200);const merged=await api(c,`/api/projects/xugu-agentic-group/change-proposals/${id}/merge`,{method:"POST",session:admin,csrf:admin.csrf,body:{}});assert.equal(merged.response.status,200);const preview=await api(c,"/api/projects/xugu-agentic-group/release/preview",{session:editor});assert.equal(preview.response.status,200);assert.equal(preview.payload.capabilities.publish,false);assert.equal((await api(c,"/api/projects/xugu-agentic-group/release/preview",{session:viewer})).response.status,404);const published=await api(c,"/api/projects/xugu-agentic-group/release/publish",{method:"POST",session:admin,csrf:admin.csrf,body:{previewToken:preview.payload.previewToken,versionLabel:"v4.3-api",acknowledged:true}});assert.equal(published.response.status,200);const audit=await api(c,"/api/projects/xugu-agentic-group/release/audit",{session:admin});assert.equal(audit.payload.items.some(item=>item.action==="project.published"),true);assert.equal((await api(c,"/api/projects/xugu-agentic-group/release/rollback",{method:"POST",session:admin,csrf:admin.csrf,body:{confirmed:true}})).response.status,200);assert.equal((await api(c,`/api/projects/other-project/change-proposals/${id}/review`,{session:admin})).response.status,404);}finally{await c.close();}});
